yo_ur_homepage:
    path:     /hello/{name}
    defaults: { _controller: YoUrBundle:Default:index }

makeFriendAction:
    path: /friend/{name1}/{name2}
    defaults: { _controller: YoUrBundle:Default:makeFriend }

createAction:
    path:     /create
    defaults: { _controller: YoUrBundle:Default:create }

displayFixAction:
    path:     /displayFix
    defaults: { _controller: YoUrBundle:Default:displayFix }

displayAction:
    path:     /display/{username}
    defaults: { _controller: YoUrBundle:Default:displayUserTimeline }

showUserAction:
    path:     /show/{username}
    defaults: { _controller: YoUrBundle:Default:showUser }