parameters:
#    yo_ur.example.class: Yo\UrBundle\Example

services:
#    yo_ur.example:
#        class: %yo_ur.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
    my_spread:
        class: Yo\UrBundle\Spread\MySpread
        arguments: ["@logger", "@jms_serializer"]
        tags:
            - { name : spy_timeline.spread }
